### ISSUE TITLE
#in_progress Escrever README.md to projeto

### ISSUE THREAD

**Issue by joellacerda** [dcTeam7/in_progress#1]
## Description

Criado uma issue para cada checkbox desta issue

Descreva os seguintes topicos:

- [x] Pre-requisitos https://github.com/dcTeam7/in_progress/issues/3
- [x] Descrição do projeto https://github.com/dcTeam7/in_progress/issues/4
- [x] Rodando o projeto localmente https://github.com/dcTeam7/in_progress/issues/6
- [x] Como fazer deploy https://github.com/dcTeam7/in_progress/issues/7
- [x] Contribuidores https://github.com/dcTeam7/in_progress/issues/8

Exemplo:
